# Generated by Django 3.0.3 on 2020-02-19 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=250)),
                ('ticket_status', models.CharField(choices=[('0', 'New'), ('1', 'In Progress'), ('2', 'Done'), ('Invalid', 'Invalid')], default='New', max_length=11)),
                ('user_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_assigned', to=settings.AUTH_USER_MODEL)),
                ('user_completed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_completed', to=settings.AUTH_USER_MODEL)),
                ('user_filled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_filled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
